### ISSUE TITLE
Unable to extract the .rar file

### ISSUE THREAD

**Issue by laycoding** [xbjxh/CurveLanes#4]
Using the unrar command ```unrar x Curvelanes.par1.rar``` to extract the downloaded file, but got:
![image](https://user-images.githubusercontent.com/17764091/92197113-751aec00-eea3-11ea-9da1-1425f423783b.png)
It seemed that I only got the test images, is there any limitation or password need to enter?
Or, what is the correct way to extract the .rar file?
Thanks a lot!

**Comment by xbjxh** [comment]
You need download all the file and extract them all.2020年9月4日 上午11:47，zhang weidong <notifications@github.com>写道：
Using the unrar command unrar x Curvelanes.par1.rar to extract the downloaded file, but got:

It seemed that I only got the test images, is there any limitation or password need to enter?
Or, what is the correct way to extract the .rar file?
Thanks a lot!

**Comment by laycoding** [comment]
Thanks for your quick response!
Actually, I already downloaded all of them, six-packs, sum 76G.
Could you please help me to check the correctness of the md5sum of which I downloaded. Here are them:
![image](https://user-images.githubusercontent.com/17764091/92204060-35f59680-eeb5-11ea-9aa3-84e4bc4dc5ad.png)
![image](https://user-images.githubusercontent.com/17764091/92204221-9684d380-eeb5-11ea-82f9-5239760665b2.png)

sorry for interrupting you.

**Comment by xbjxh** [comment]
I think your part1.rar is broken. My MD5 for that file is:
Curvelanes.par1.rar     57c3ba0b79db512e1ec1c4a90d6ba254
Curvelanes.par2.rar     ce973dcd7f0d835a4921bf87f833d123
Curvelanes.par3.rar     fc00a9844433a295d8dc9002e6e3cdbf
Curvelanes.par4.rar     e0d56940ffbe127a67bca5484872be8f

**Comment by xbjxh** [comment]
I think your part1.rar is broken. My MD5 for that file is:
Curvelanes.par1.rar 57c3ba0b79db512e1ec1c4a90d6ba254
Curvelanes.par2.rar ce973dcd7f0d835a4921bf87f833d123
Curvelanes.par3.rar fc00a9844433a295d8dc9002e6e3cdbf
Curvelanes.par4.rar e0d56940ffbe127a67bca5484872be8f
Curvelanes.par5.rar be66dfac5ad00e0aee5b74a307cc94dc
Curvelanes.par6.rar cb8125711247a41a38ac9903b2990b03
